# Generated by Django 5.0.14 on 2025-12-07 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0003_make_user_field_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="toolexecution",
            name="azure_function_invoked",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="toolexecution",
            name="function_execution_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="toolexecution",
            name="input_blob_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="toolexecution",
            name="output_blob_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name="toolexecution",
            index=models.Index(
                fields=["function_execution_id"], name="tool_execut_functio_905fff_idx"
            ),
        ),
    ]
